/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Feature_COLON = 1,
  anon_sym_SPACE = 2,
  aux_sym_title_token1 = 3,
  sym_description_line = 4,
  anon_sym_Background_COLON = 5,
  anon_sym_LF = 6,
  anon_sym_Scenario_COLON = 7,
  anon_sym_Given = 8,
  anon_sym_When = 9,
  anon_sym_Then = 10,
  anon_sym_And = 11,
  sym__newline = 12,
  sym_source_file = 13,
  sym_feature = 14,
  sym_title = 15,
  sym_description = 16,
  sym_background = 17,
  sym_scenario = 18,
  sym_steps = 19,
  sym_given = 20,
  sym_when = 21,
  sym_then = 22,
  sym_and = 23,
  sym_step = 24,
  aux_sym_feature_repeat1 = 25,
  aux_sym_description_repeat1 = 26,
  aux_sym_steps_repeat1 = 27,
  aux_sym_given_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Feature_COLON] = "Feature:",
  [anon_sym_SPACE] = " ",
  [aux_sym_title_token1] = "title_token1",
  [sym_description_line] = "description_line",
  [anon_sym_Background_COLON] = "Background:",
  [anon_sym_LF] = "\n",
  [anon_sym_Scenario_COLON] = "Scenario:",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_feature] = "feature",
  [sym_title] = "title",
  [sym_description] = "description",
  [sym_background] = "background",
  [sym_scenario] = "scenario",
  [sym_steps] = "steps",
  [sym_given] = "given",
  [sym_when] = "when",
  [sym_then] = "then",
  [sym_and] = "and",
  [sym_step] = "step",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_steps_repeat1] = "steps_repeat1",
  [aux_sym_given_repeat1] = "given_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Feature_COLON] = anon_sym_Feature_COLON,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [sym_description_line] = sym_description_line,
  [anon_sym_Background_COLON] = anon_sym_Background_COLON,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_Scenario_COLON] = anon_sym_Scenario_COLON,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_feature] = sym_feature,
  [sym_title] = sym_title,
  [sym_description] = sym_description,
  [sym_background] = sym_background,
  [sym_scenario] = sym_scenario,
  [sym_steps] = sym_steps,
  [sym_given] = sym_given,
  [sym_when] = sym_when,
  [sym_then] = sym_then,
  [sym_and] = sym_and,
  [sym_step] = sym_step,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_steps_repeat1] = aux_sym_steps_repeat1,
  [aux_sym_given_repeat1] = aux_sym_given_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Feature_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Background_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Scenario_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_background] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario] = {
    .visible = true,
    .named = true,
  },
  [sym_steps] = {
    .visible = true,
    .named = true,
  },
  [sym_given] = {
    .visible = true,
    .named = true,
  },
  [sym_when] = {
    .visible = true,
    .named = true,
  },
  [sym_then] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_steps_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_given_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 19,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      if (lookahead == 'A') ADVANCE(30);
      if (lookahead == 'B') ADVANCE(12);
      if (lookahead == 'F') ADVANCE(20);
      if (lookahead == 'G') ADVANCE(27);
      if (lookahead == 'S') ADVANCE(15);
      if (lookahead == 'T') ADVANCE(25);
      if (lookahead == 'W') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == 'B') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '\r') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(73);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(71);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(77);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 44:
      if (lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 45:
      if (eof) ADVANCE(46);
      if (lookahead == '\n') SKIP(45);
      if (lookahead == 'B') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_Feature_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_title_token1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(4);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == 'B') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == ':') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'c') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'd') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'g') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'k') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_Background_COLON);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_Scenario_COLON);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '\r') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 45},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 45},
  [18] = {.lex_state = 45},
  [19] = {.lex_state = 45},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 45},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Feature_COLON] = ACTIONS(1),
    [anon_sym_Background_COLON] = ACTIONS(1),
    [anon_sym_Scenario_COLON] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_feature] = STATE(42),
    [anon_sym_Feature_COLON] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      sym_description_line,
    ACTIONS(9), 1,
      anon_sym_Background_COLON,
    ACTIONS(11), 1,
      anon_sym_Scenario_COLON,
    STATE(15), 1,
      sym_description,
    STATE(17), 1,
      aux_sym_description_repeat1,
    STATE(21), 1,
      sym_background,
    STATE(23), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [26] = 5,
    ACTIONS(15), 1,
      anon_sym_Given,
    ACTIONS(17), 1,
      anon_sym_When,
    ACTIONS(19), 1,
      anon_sym_Then,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
    STATE(4), 4,
      sym_given,
      sym_when,
      sym_then,
      aux_sym_steps_repeat1,
  [46] = 5,
    ACTIONS(23), 1,
      anon_sym_Given,
    ACTIONS(26), 1,
      anon_sym_When,
    ACTIONS(29), 1,
      anon_sym_Then,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
    STATE(4), 4,
      sym_given,
      sym_when,
      sym_then,
      aux_sym_steps_repeat1,
  [66] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(8), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(32), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [81] = 3,
    ACTIONS(38), 1,
      anon_sym_And,
    STATE(6), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(36), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [96] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(6), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [111] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(6), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [126] = 5,
    ACTIONS(15), 1,
      anon_sym_Given,
    ACTIONS(17), 1,
      anon_sym_When,
    ACTIONS(19), 1,
      anon_sym_Then,
    STATE(31), 1,
      sym_steps,
    STATE(3), 4,
      sym_given,
      sym_when,
      sym_then,
      aux_sym_steps_repeat1,
  [145] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(6), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(45), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [160] = 5,
    ACTIONS(15), 1,
      anon_sym_Given,
    ACTIONS(17), 1,
      anon_sym_When,
    ACTIONS(19), 1,
      anon_sym_Then,
    STATE(35), 1,
      sym_steps,
    STATE(3), 4,
      sym_given,
      sym_when,
      sym_then,
      aux_sym_steps_repeat1,
  [179] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(10), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(47), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [194] = 3,
    ACTIONS(34), 1,
      anon_sym_And,
    STATE(7), 2,
      sym_and,
      aux_sym_given_repeat1,
    ACTIONS(49), 5,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [209] = 1,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
  [218] = 5,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_Background_COLON,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    STATE(25), 1,
      sym_background,
    STATE(26), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [235] = 1,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
  [244] = 4,
    ACTIONS(7), 1,
      sym_description_line,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_description_repeat1,
    ACTIONS(63), 2,
      anon_sym_Background_COLON,
      anon_sym_Scenario_COLON,
  [258] = 4,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym_description_line,
    STATE(18), 1,
      aux_sym_description_repeat1,
    ACTIONS(70), 2,
      anon_sym_Background_COLON,
      anon_sym_Scenario_COLON,
  [272] = 2,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 3,
      sym_description_line,
      anon_sym_Background_COLON,
      anon_sym_Scenario_COLON,
  [281] = 3,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [292] = 3,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    STATE(26), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [303] = 2,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 3,
      sym_description_line,
      anon_sym_Background_COLON,
      anon_sym_Scenario_COLON,
  [312] = 3,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    STATE(24), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [323] = 3,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_Scenario_COLON,
    STATE(24), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [334] = 3,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [345] = 3,
    ACTIONS(57), 1,
      anon_sym_Scenario_COLON,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym_scenario,
      aux_sym_feature_repeat1,
  [356] = 1,
    ACTIONS(72), 3,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
  [362] = 2,
    ACTIONS(85), 1,
      aux_sym_title_token1,
    STATE(12), 1,
      sym_step,
  [369] = 2,
    ACTIONS(85), 1,
      aux_sym_title_token1,
    STATE(5), 1,
      sym_step,
  [376] = 2,
    ACTIONS(85), 1,
      aux_sym_title_token1,
    STATE(13), 1,
      sym_step,
  [383] = 1,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
  [388] = 2,
    ACTIONS(89), 1,
      aux_sym_title_token1,
    STATE(11), 1,
      sym_title,
  [395] = 2,
    ACTIONS(91), 1,
      aux_sym_title_token1,
    STATE(2), 1,
      sym_title,
  [402] = 2,
    ACTIONS(85), 1,
      aux_sym_title_token1,
    STATE(16), 1,
      sym_step,
  [409] = 1,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      anon_sym_Scenario_COLON,
  [414] = 1,
    ACTIONS(95), 1,
      anon_sym_SPACE,
  [418] = 1,
    ACTIONS(97), 1,
      anon_sym_SPACE,
  [422] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [426] = 1,
    ACTIONS(101), 1,
      anon_sym_SPACE,
  [430] = 1,
    ACTIONS(103), 1,
      sym__newline,
  [434] = 1,
    ACTIONS(105), 1,
      anon_sym_SPACE,
  [438] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
  [442] = 1,
    ACTIONS(109), 1,
      anon_sym_LF,
  [446] = 1,
    ACTIONS(111), 1,
      anon_sym_SPACE,
  [450] = 1,
    ACTIONS(113), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 81,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 111,
  [SMALL_STATE(9)] = 126,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 160,
  [SMALL_STATE(12)] = 179,
  [SMALL_STATE(13)] = 194,
  [SMALL_STATE(14)] = 209,
  [SMALL_STATE(15)] = 218,
  [SMALL_STATE(16)] = 235,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 281,
  [SMALL_STATE(21)] = 292,
  [SMALL_STATE(22)] = 303,
  [SMALL_STATE(23)] = 312,
  [SMALL_STATE(24)] = 323,
  [SMALL_STATE(25)] = 334,
  [SMALL_STATE(26)] = 345,
  [SMALL_STATE(27)] = 356,
  [SMALL_STATE(28)] = 362,
  [SMALL_STATE(29)] = 369,
  [SMALL_STATE(30)] = 376,
  [SMALL_STATE(31)] = 383,
  [SMALL_STATE(32)] = 388,
  [SMALL_STATE(33)] = 395,
  [SMALL_STATE(34)] = 402,
  [SMALL_STATE(35)] = 409,
  [SMALL_STATE(36)] = 414,
  [SMALL_STATE(37)] = 418,
  [SMALL_STATE(38)] = 422,
  [SMALL_STATE(39)] = 426,
  [SMALL_STATE(40)] = 430,
  [SMALL_STATE(41)] = 434,
  [SMALL_STATE(42)] = 438,
  [SMALL_STATE(43)] = 442,
  [SMALL_STATE(44)] = 446,
  [SMALL_STATE(45)] = 450,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_steps, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_steps_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_steps_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_steps_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_steps_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_given, 3, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_given_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_given_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_given, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_then, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_then, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_background, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gherkin(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gherkin",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
